
analysis_task:
  description: >
    1. This research is about: {topic}
    2. Here is the content: {content}
    2. Read the content provided and understand what it is about.
    3. Identify the topics and sub topics along with metadata of each topic. Example of metadata is whether the topic is general or specific and need depth or breadth.
    4. Create a list of topics and sub topics to do the thorough research on the subject
    5. List of topics and sub topics must be arranged in a way which takes the users from understandig the problem statement to final solution, approaches & limitations.
    6. Adhere to the topic and content. Dont add any additional material and topic from your own.
    7. Dont add any topic or subtopic on your own.
  expected_output: >
    A priority ordered list of topic and subtopics with the metadata.
  agent: analyst
  output_file: ai_blogger/crew_ai/output/outline.md

research_task:
  description: >    
    1. You will get a list of topics and sub topic with metadata like whether it is a general or specific topic and whether it needs depth or breadth research.
    2. You should do the research about every topic in the order provided and write it in a markdown file.
    3. Your research must be factual and aligned to the topic provided.
    4. Depth is important for technical topics.    
    5. Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive research document with well-organized sections covering all the requested aspects of topic.
  agent: researcher
  context:
    - analysis_task
  output_file: ai_blogger/crew_ai/output/research.md
