
analysis_task:
  description: >
    1. This research is about: {topic}
    2. Here is the content: {content}
    2. Read the content provided and understand what it is about.
    3. Identify the topics and sub topics along with metadata of each topic. Example of metadata is whether the topic is general or specific and need depth or breadth.
    4. Create a list of topics and sub topics to do the thorough research on the subject
    5. List of topics and sub topics must be arranged in a way which takes the users from understandig the problem statement to final solution, approaches & limitations.
    6. Adhere to the topic and content. Dont add any additional material and topic from your own.
    7. Dont add any topic or subtopic on your own.
  expected_output: >
    A priority ordered list of topic and subtopics with the metadata.
  agent: analyst
  output_file: ai_blogger/crew_ai/output/outline.md


editor_task:
  description: >
    1. Read the file: {file_path}    
    2. For each topic in the file, call the sub agent.
    3. Wait untill sub agent has finished the task before passing next topic in the loop.    
    4. Dont add any topic or subtopic on your own. Do not call LLM.
  expected_output: >
    Final status on each sub topic
  agent: editor


writer_task:
  description: >
    1. You will be called multiple times with an input. 
    1. Write the passed input in the file.
  expected_output: >
    output file written with all the topics
  agent: writer
  output_file: ai_blogger/crew_ai/output/research.md


# research_task:
#   description: >    
#     1. Read the file: {file_path}
#     2. Understand the topics and sub topics.
#     3. Start a loop and do the deep research for each topic.
#     5. Your research must be factual and aligned to the topic provided.
#     6. Depth is important for technical topics.    
#     7. Make sure to organize your findings in a structured format with clear sections.
#     8. Append the research for each topic in the output file {output_file}
#   expected_output: >
#     A comprehensive research document with well-organized sections covering all the requested aspects of topic.
#   agent: researcher
#   output_file: ai_blogger/crew_ai/output/research.md
